apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresDatabase }}
  POSTGRES_USER: {{ .Values.postgresql.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | quote }}
