apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    app: postgresql
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresDatabase }}
  POSTGRES_USER: {{ .Values.postgresql.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword }}
