apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgresql-ingress
spec:
  rules:
    - host: postgres.harness-demo.site
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: postgresql
                port:
                  number: 5432