apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgresql.fullname" . }}-pv
  labels:
    app: postgresql
spec:
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  hostPath:
    path: /data/postgresql
