apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
