apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  storageClassName: manual
