apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
spec:
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  hostPath:
    path: /data/postgresql
