apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce  # Ensure this matches your requirements
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  storageClassName: standard  # Replace with your desired storage class
