apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    type: local
    app: postgresql
spec:
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  hostPath:
    path: /data2/postgresql
