apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    app: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
  selector:
    app: postgresql
