apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ template "postgres.name" . }}
